aws_region             = "us-east-1"
aws_profile            = "default"
pinpoint_name          = "GBProductionPinpointApp"
sms_sender_id          = "GainBridge"
# sms_origination_number = "+12148620730"
# sms_message_type       = "TRANSACTIONAL"
