instance_alias           = "demo-insurance"
identity_management_type = "CONNECT_MANAGED"
common_name              = "Demo Test"
lambda_function_arn      = "arn:aws:lambda:us-east-1:123456789101:function:demo-function"
time_zone                = "EST"
# phone_number              = "+1234567890"
